import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  moduleCosmetiqueSidebar: [
    { type: 'autogenerated', dirName: 'module-cosmetique' }
  ],
  moduleStaffSidebar: [
    { type: 'autogenerated', dirName: 'module-staff' }
  ],
};

export default sidebars;
